--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayush/Pictures/wallpapers/HD wallpaper_ 5K, CGI, Dark, Mountains, Sunrise, Minimal.jpeg"

-- Special
background="#010612"
foreground="#e2dcd0"
cursor="#e2dcd0"

-- Colors
color0="#010612"
color1="#366B8C"
color2="#457B97"
color3="#8E7C88"
color4="#6195AA"
color5="#9AAFB0"
color6="#CBB2A1"
color7="#e2dcd0"
color8="#9e9a91"
color9="#366B8C"
color10="#457B97"
color11="#8E7C88"
color12="#6195AA"
color13="#9AAFB0"
color14="#CBB2A1"
color15="#e2dcd0"
