# Shell variables
# Generated by 'wal'
wallpaper='/home/ayush/Pictures/wallpapers/e2c71e97-9f7c-4c71-8638-c9e58bdfa65a.png'

# Special
background='#131924'
foreground='#cde2e7'
cursor='#cde2e7'

# Colors
color0='#131924'
color1='#68ABB7'
color2='#6FA8B8'
color3='#77B2C6'
color4='#84B1BB'
color5='#88BAC9'
color6='#93C7D4'
color7='#cde2e7'
color8='#8f9ea1'
color9='#68ABB7'
color10='#6FA8B8'
color11='#77B2C6'
color12='#84B1BB'
color13='#88BAC9'
color14='#93C7D4'
color15='#cde2e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
