# Shell variables
# Generated by 'wal'
wallpaper='/home/ayush/Pictures/wallpapers/xiao.png'

# Special
background='#002723'
foreground='#bfc9c8'
cursor='#bfc9c8'

# Colors
color0='#002723'
color1='#00c5b4'
color2='#00b7ac'
color3='#01a9a7'
color4='#019baa'
color5='#0188aa'
color6='#0270aa'
color7='#bfc9c8'
color8='#3f5d5a'
color9='#00c5b4'
color10='#00b7ac'
color11='#01a9a7'
color12='#019baa'
color13='#0188aa'
color14='#0270aa'
color15='#bfc9c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
