--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayush/Pictures/wallpapers/candlin.jpg"

-- Special
background="#12181a"
foreground="#bbd4da"
cursor="#bbd4da"

-- Colors
color0="#12181a"
color1="#2D718D"
color2="#47758C"
color3="#348CA6"
color4="#549DB2"
color5="#6CB4C5"
color6="#79C0CE"
color7="#bbd4da"
color8="#829498"
color9="#2D718D"
color10="#47758C"
color11="#348CA6"
color12="#549DB2"
color13="#6CB4C5"
color14="#79C0CE"
color15="#bbd4da"
