# Shell variables
# Generated by 'wal'
wallpaper='/home/ayush/Pictures/wallpapers/candlin.jpg'

# Special
background='#12181a'
foreground='#bbd4da'
cursor='#bbd4da'

# Colors
color0='#12181a'
color1='#2D718D'
color2='#47758C'
color3='#348CA6'
color4='#549DB2'
color5='#6CB4C5'
color6='#79C0CE'
color7='#bbd4da'
color8='#829498'
color9='#2D718D'
color10='#47758C'
color11='#348CA6'
color12='#549DB2'
color13='#6CB4C5'
color14='#79C0CE'
color15='#bbd4da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
