--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayush/Pictures/wallpapers/e2c71e97-9f7c-4c71-8638-c9e58bdfa65a.png"

-- Special
background="#131924"
foreground="#cde2e7"
cursor="#cde2e7"

-- Colors
color0="#131924"
color1="#68ABB7"
color2="#6FA8B8"
color3="#77B2C6"
color4="#84B1BB"
color5="#88BAC9"
color6="#93C7D4"
color7="#cde2e7"
color8="#8f9ea1"
color9="#68ABB7"
color10="#6FA8B8"
color11="#77B2C6"
color12="#84B1BB"
color13="#88BAC9"
color14="#93C7D4"
color15="#cde2e7"
