#! /bin/sh
#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh 
$HOME/.config/picom/picom.conf

bspc monitor -d 1 2 3 4 5 6 7 
bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config ignore_ewmh_focus	 true


#############COLORS###############

."~/.cache/wal/colors.sh"


bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"


#mouse focus
bspc config focus_follows_pointer true
xinput set-prop "MSFT0002:00 04F3:317F Touchpad" "libinput Tapping Enabled" 1 &
xinput set-prop "MSFT0002:00 04F3:317F Touchpad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "MSFT0002:00 04F3:317F Touchpad" "libinput Natural Scrolling Enabled" 1 &
libinput-gestures-setup start &
xsetroot -cursor_name left_ptr &

#autostart


nitrogen --restore &
picom &
dunst &
geary --hidden &
corectrl &
#slack -u &
#whatsdesk &
rclone --vfs-cache-mode writes mount "onedrive":  ~/onedrive &

bspc rule -a slack -o desktop='^7'
bspc rule -a whatsdesk -o desktop='^7'
bspc rule -add Google-chrome desktop='^4'
bspc rule -a "alacritty:ncspot"NCSPOT -o desktop='^1'
bspc rule -a AndroidMessages -o desktop='^4'
bspc rule -a "microsoft teams - preview" -o desktop='^6'
bspc rule -a Zathura state=tiled
