#! /bin/sh
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/.config/picom/picom.conf

bspc monitor -d 1 2 3 4 5 6 7
bspc config border_width 0
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
#bspc config gapless_monocle      true
bspc config single_monocle true
bspc config ignore_ewmh_focus true

#############COLORS###############

bspc config normal_border_color \#2e323a
bspc config active_border_color \#00c5b4
bspc config focused_border_color \#61afef
# Use the line below if you are on bspwm >= 0.9.4
# bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#mouse focus
bspc config focus_follows_pointer true
xinput set-prop "MSFT0002:00 04F3:317F Touchpad" "libinput Tapping Enabled" 1 &
xinput set-prop "MSFT0002:00 04F3:317F Touchpad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "MSFT0002:00 04F3:317F Touchpad" "libinput Natural Scrolling Enabled" 1 &
libinput-gestures-setup start &
xsetroot -cursor_name left_ptr &

#autostart

xsettingsd &
xset -b &
# gnome-keyring-daemon &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
picom &
dunst &
geary --hidden &
solaar -w hide &
# slack -u &
whatsdesk &
umount onedrive &
# rclone --vfs-cache-mode writes mount "onedrive:Year 2/Sem 4" ~/onedrive/Sem\ 4 &
# rclone --vfs-cache-mode writes mount "onedrive:Books" ~/onedrive/Books/ &
rclone --vfs-cache-mode writes mount "onedrive":  ~/onedrive &

bspc rule -a slack -o desktop='^7'
bspc rule -a whatsdesk -o desktop='^7'
bspc rule -a AndroidMessages -o desktop='^7'
bspc rule -a "microsoft teams - preview" -o desktop='^6'
bspc rule -a Zathura state=tiled
