--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayush/Pictures/wallpapers/andre-benz-JBkwaYMuhdc-unsplash.jpg"

-- Special
background="#0b0f11"
foreground="#aabcc2"
cursor="#aabcc2"

-- Colors
color0="#0b0f11"
color1="#1C4452"
color2="#294753"
color3="#2E5766"
color4="#346472"
color5="#525C61"
color6="#4F7885"
color7="#aabcc2"
color8="#768387"
color9="#1C4452"
color10="#294753"
color11="#2E5766"
color12="#346472"
color13="#525C61"
color14="#4F7885"
color15="#aabcc2"
