# Shell variables
# Generated by 'wal'
wallpaper='/home/ayush/Pictures/wallpapers/andre-benz-JBkwaYMuhdc-unsplash.jpg'

# Special
background='#0b0f11'
foreground='#aabcc2'
cursor='#aabcc2'

# Colors
color0='#0b0f11'
color1='#1C4452'
color2='#294753'
color3='#2E5766'
color4='#346472'
color5='#525C61'
color6='#4F7885'
color7='#aabcc2'
color8='#768387'
color9='#1C4452'
color10='#294753'
color11='#2E5766'
color12='#346472'
color13='#525C61'
color14='#4F7885'
color15='#aabcc2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
